---
name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: install, build, and test
        run: make
        env:
          CI: true
