---
name: Node CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: npm install, build, and test
        run: make
        env:
          CI: true
